"""
GRPO Agent — online reinforcement learning via W&B ART + RULER.

Uses ART's ServerlessBackend (CoreWeave GPU) to run GRPO training:
  1. Load grpo_prompts_*.jsonl — list of {"prompt": "..."} generated by DataSimulator
  2. Build WritingStyleProfile from memory (RULER's scoring rubric)
  3. ART training loop:
       for each prompt:
         a. Model generates N completions (via ART's openai_client)
         b. RULER (Gemini Flash) scores each completion [0.0, 1.0]
         c. Trajectories assembled with reward = RULER score
         d. backend.train() runs GRPO update
  4. W&B logs reward curves automatically via ART
  5. Save model artifact for post-GRPO eval

Auth:
  WANDB_API_KEY  — ServerlessBackend + W&B logging
  GOOGLE_API_KEY — RULER judge (Gemini Flash)
  OPENPIPE_API_KEY — optional OpenPipe trace logging
"""

from __future__ import annotations

import asyncio
import json
import os
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


# ── Result ───────────────────────────────────────────────────────────────────


@dataclass
class GRPOResult:
    model_name: str
    project: str
    base_model: str           # SFT model name we started from
    prompts_trained: int
    total_steps: int
    final_reward: float = 0.0
    trained_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> dict:
        return {
            "model_name": self.model_name,
            "project": self.project,
            "base_model": self.base_model,
            "prompts_trained": self.prompts_trained,
            "total_steps": self.total_steps,
            "final_reward": self.final_reward,
            "trained_at": self.trained_at.isoformat(),
        }


# ── GRPO Agent ───────────────────────────────────────────────────────────────


class GRPOAgent:
    """
    GRPO style-alignment training via W&B ART + RULER.

    For each GRPO prompt, the agent:
      - Generates `num_generations` completions from the current model
      - Scores each with RULER (Gemini Flash) against the user's writing style
      - Uses ART's GRPO to update the model toward higher-reward completions

    Args:
        sft_model_name:    ART model name from SFTResult (used as base_model)
        model_name:        ART model name for this GRPO run
        project:           W&B project
        num_generations:   Completions per prompt (4 recommended — more = better GRPO signal)
        steps_per_save:    Save checkpoint every N steps
        learning_rate:     GRPO learning rate
        max_new_tokens:    Max tokens per completion
        use_serverless:    True → CoreWeave; False → local GPU
    """

    DEFAULT_PROJECT = "openclawmini"
    PERSONA_SYSTEM = (
        "You are {user_name}. Answer all questions as yourself in first person. "
        "Write emails, messages, and posts the way you naturally would. "
        "Be authentic — draw on your background, experiences, and communication style."
    )

    def __init__(
        self,
        sft_model_name: str,
        model_name: str = "openclawmini-grpo",
        project: str = DEFAULT_PROJECT,
        num_generations: int = 4,
        learning_rate: float = 5e-6,
        max_new_tokens: int = 300,
        use_serverless: bool = True,
        wandb_api_key: Optional[str] = None,
        google_api_key: Optional[str] = None,
    ) -> None:
        self.sft_model_name = sft_model_name
        self.model_name = model_name
        self.project = project
        self.num_generations = num_generations
        self.learning_rate = learning_rate
        self.max_new_tokens = max_new_tokens
        self.use_serverless = use_serverless
        self._wandb_api_key = wandb_api_key or os.getenv("WANDB_API_KEY", "")
        self._google_api_key = google_api_key or os.getenv("GOOGLE_API_KEY", "")

    # ── Public API ──────────────────────────────────────────────

    def train(
        self,
        grpo_jsonl_path: Path,
        memory,
        user_name: str = "",
    ) -> GRPOResult:
        """
        Run GRPO training. Blocks until training is complete.

        Args:
            grpo_jsonl_path: Path to grpo_prompts_*.jsonl with {"prompt": "..."} per line.
            memory: Memory object (used to build RULER style profile).
            user_name: User's name for persona system prompt.
        """
        return asyncio.run(self._train_async(grpo_jsonl_path, memory, user_name))

    # ── Internal async logic ────────────────────────────────────

    async def _train_async(
        self,
        grpo_jsonl_path: Path,
        memory,
        user_name: str,
    ) -> GRPOResult:
        try:
            import art  # type: ignore[import]
        except ImportError:
            raise ImportError("ART not installed. Run: pip install openpipe-art")

        from openclawmini.training.ruler import RULER, WritingStyleProfile

        # Load prompts
        prompts = self._load_prompts(grpo_jsonl_path)
        if not prompts:
            raise ValueError(f"No prompts found in {grpo_jsonl_path}")

        # Build RULER + style profile
        ruler = RULER(api_key=self._google_api_key)
        style_profile = WritingStyleProfile.from_memory(memory, user_name=user_name)
        system_msg = self.PERSONA_SYSTEM.format(user_name=user_name or "yourself")

        # Build ART model (starting from SFT checkpoint)
        model = art.TrainableModel(
            name=self.model_name,
            project=self.project,
            base_model=self.sft_model_name,   # Start from SFT model
        )

        if self.use_serverless:
            if not self._wandb_api_key:
                raise RuntimeError("WANDB_API_KEY required for ART ServerlessBackend.")
            backend = art.ServerlessBackend(api_key=self._wandb_api_key)
        else:
            backend = art.LocalBackend()

        await model.register(backend)
        openai_client = model.openai_client()

        # ── Training loop ───────────────────────────────────────
        start_step = await model.get_step()
        total_reward = 0.0
        total_trajectories = 0

        data_iterator = art.trajectory_group_batches(
            items=[{"prompt": p} for p in prompts],
            groups_per_step=4,
            num_epochs=1,
            initial_step=start_step,
        )

        for batch in data_iterator:
            train_groups = await art.gather_trajectory_groups(
                (
                    art.TrajectoryGroup(
                        self._rollout(
                            openai_client=openai_client,
                            model_name=self.model_name,
                            prompt_text=item["prompt"],
                            system_msg=system_msg,
                            ruler=ruler,
                            style_profile=style_profile,
                        )
                        for _ in range(self.num_generations)
                    )
                    for item in batch.items
                ),
                pbar_desc=f"step {batch.step}",
                max_exceptions=self.num_generations - 1,  # tolerate some failures
            )

            # Filter groups that have at least 2 valid trajectories
            valid_groups = []
            for group in train_groups:
                valid = [t for t in group if isinstance(t, art.Trajectory)]
                if len(valid) >= 2:
                    valid_groups.append(valid)
                    for t in valid:
                        total_reward += t.reward
                        total_trajectories += 1

            if not valid_groups:
                continue

            result = await backend.train(
                model,
                valid_groups,
                learning_rate=self.learning_rate,
            )
            await model.log(
                valid_groups,
                metrics=result.metrics,
                step=result.step,
                split="train",
            )

        final_avg_reward = total_reward / max(total_trajectories, 1)
        print(f"  GRPO complete. Avg reward: {final_avg_reward:.3f}  Steps: {batch.step}")

        grpo_result = GRPOResult(
            model_name=self.model_name,
            project=self.project,
            base_model=self.sft_model_name,
            prompts_trained=len(prompts),
            total_steps=batch.step,
            final_reward=final_avg_reward,
        )

        # Save metadata
        output_dir = Path("./data/models/grpo")
        output_dir.mkdir(parents=True, exist_ok=True)
        meta_path = output_dir / f"grpo_result_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.json"
        meta_path.write_text(json.dumps(grpo_result.to_dict(), indent=2))

        return grpo_result

    async def _rollout(
        self,
        openai_client,
        model_name: str,
        prompt_text: str,
        system_msg: str,
        ruler,
        style_profile,
    ):
        """Generate one completion and score with RULER."""
        import art  # type: ignore[import]

        messages = [
            {"role": "system", "content": system_msg},
            {"role": "user", "content": prompt_text},
        ]

        try:
            completion = await openai_client.chat.completions.create(
                messages=messages,
                model=model_name,
                max_tokens=self.max_new_tokens,
                temperature=1.0,
                logprobs=True,
            )
            choice = completion.choices[0]
            response_text = choice.message.content or ""

            # RULER scores the response against user's writing style
            reward = ruler.score(response_text, style_profile)

            return art.Trajectory(
                messages_and_choices=[*messages, choice],
                reward=reward,
                metrics={"ruler_score": reward},
            )

        except Exception as e:
            # Return a failed trajectory (will be filtered out)
            return Exception(f"Rollout failed: {e}")

    def _load_prompts(self, path: Path) -> list[str]:
        """Load prompts from grpo_prompts_*.jsonl."""
        prompts = []
        try:
            with open(path) as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        data = json.loads(line)
                        prompt = data.get("prompt", "")
                        if prompt:
                            prompts.append(prompt)
                    except json.JSONDecodeError:
                        continue
        except FileNotFoundError:
            pass
        return prompts

    # ── Factory ────────────────────────────────────────────────

    @classmethod
    def from_sft_result(cls, sft_result, config=None, user_name: str = "") -> "GRPOAgent":
        """Build GRPOAgent from a completed SFTResult."""
        grpo_name = f"openclawmini-grpo-{user_name.lower().replace(' ', '-')}" if user_name else "openclawmini-grpo"

        lr = 5e-6
        n_gen = 4
        if config is not None:
            lr = getattr(config.training, "grpo_steps", 100) * 5e-8  # scale with steps
            n_gen = getattr(config.training, "grpo_trajectories_per_scenario", 4)

        return cls(
            sft_model_name=sft_result.model_name,
            model_name=grpo_name,
            project=sft_result.project,
            num_generations=n_gen,
            learning_rate=lr,
        )

    @classmethod
    def from_env(cls, sft_model_name: str, config=None, user_name: str = "") -> "GRPOAgent":
        """Build from environment variables."""
        grpo_name = (
            f"openclawmini-grpo-{user_name.lower().replace(' ', '-')}"
            if user_name else "openclawmini-grpo"
        )
        return cls(
            sft_model_name=sft_model_name,
            model_name=grpo_name,
            project=os.getenv("WANDB_PROJECT", cls.DEFAULT_PROJECT),
        )
